using WCSharp.Shared.Data;

/// <summary>
/// This class is auto-generated by WCSharp.ConstantGenerator.
/// </summary>
public static class Regions
{
	public static Rectangle WarriorSelectRegion { get; set; } = new Rectangle(-3264f, -3264f, -3136f, -3136f);
	public static Rectangle MageSelectRegion { get; set; } = new Rectangle(-3008f, -3264f, -2880f, -3136f);
	public static Rectangle ArcherSelectRegion { get; set; } = new Rectangle(-2752f, -3264f, -2624f, -3136f);
	public static Rectangle HeroSpawnRegion { get; set; } = new Rectangle(-2176f, -3456f, -2048f, -3328f);
	public static Rectangle JobAdvancementRegion { get; set; } = new Rectangle(-2176f, -2816f, -2048f, -2688f);
	public static Rectangle GameStartRegion { get; set; } = new Rectangle(-3008f, -3520f, -2880f, -3392f);

}