using WCSharp.Shared.Data;

/// <summary>
/// This class is auto-generated by WCSharp.ConstantGenerator.
/// </summary>
public static class Regions
{
	public static Rectangle WarriorSelectRegion { get; set; } = new Rectangle(-29824f, -29120f, -29696f, -28992f);
	public static Rectangle MageSelectRegion { get; set; } = new Rectangle(-29568f, -29120f, -29440f, -28992f);
	public static Rectangle ArcherSelectRegion { get; set; } = new Rectangle(-29312f, -29120f, -29184f, -28992f);
	public static Rectangle HeroSpawnRegion { get; set; } = new Rectangle(-2528f, -3456f, -2400f, -3328f);
	public static Rectangle JobAdvancementRegion { get; set; } = new Rectangle(-2176f, -2816f, -2048f, -2688f);
	public static Rectangle GameStartRegion { get; set; } = new Rectangle(-29536f, -29664f, -29408f, -29536f);

}